- name: install development tools
  yum: 
    name: "{{ item }} "
    state: installed
  with_items:
    - "autoconf"
    - "automake"
    - "bison"
    - "byacc"
    - "cscope"
    - "ctags"
    - "elfutils"
    - "flex"
    - "gcc-c++"
    - "gcc"
    - "gettext"
    - "git"
    - "intltool"
    - "kernel-devel"
    - "libtool"
    - "make"
    - "mariadb"
    - "nano"
    - "nginx"
    - "openssl-devel"
    - "patch"
    - "patchutils"
    - "pkgconfig"
    - "systemtap"
    - "tree"
    - "vim"
    - "wget"
